title: <p align="center">Saikrupa Purushothaman</p>
logo: /assets/img/Saikrupa.png
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/saikrupa-purushothaman/">LinkedIn</a>   
  <a href="https://github.com/psaikrupa">GitHub</a>
  <br>
  I'm a Data and Analytics Consultant with over 15 years of experience in this field. 
  Currently exploring Maching Learning and Artificial Intelligence.
  </p>
theme: jekyll-theme-minimal
